a: gg
spring:
  application:
    name: product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zl
    url: jdbc:mysql://localhost:3306/clou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
mybatis:
  config-location: classpath:sqlConfig.xml
  mapper-locations: classpath:mapper.xml
